
services:
  auth-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  booking-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  notification-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  payment-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  pets-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  review-api:
    environment:
      LOG_LEVEL: Debug
      HEALTHCHECK__ENABLED: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
