version: '3.8'

networks:
  petcare_net:
    driver: bridge

services:

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: petcare_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://petcare_kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@petcare_kafka:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "WubDWjzVeUus0p32WsEu4g=="
    networks:
      - petcare_net

  auth-api:
    build:
      context: .
      dockerfile: Auth/PetCare.Auth.Api/Dockerfile
    container_name: petcare_auth
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AuthDatabase: "Server=192.168.1.54,1433;Database=PetCareAuthDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Jwt__Secret: "TuClaveSuperSecreta!123!CambiaEstoEnProduccion"
      Jwt__Issuer: "http://petcare_auth"
      Jwt__Audience: "PetCareClientApp"
    ports:
      - "5001:80"
    networks:
      - petcare_net

  pets-api:
    build:
      context: .
      dockerfile: Pets/PetCare.Pets.Api/Dockerfile
    container_name: petcare_pets
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PetsDatabase: "Server=192.168.1.54,1433;Database=PetCarePetsDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Jwt__Secret: "TuClaveSuperSecreta!123!CambiaEstoEnProduccion"
      Jwt__Issuer: "http://petcare_auth"
      Jwt__Audience: "PetCareClientApp"
    ports:
      - "5002:80"
    networks:
      - petcare_net
    depends_on:
      - auth-api

  booking-api:
    build:
      context: .
      dockerfile: Booking/PetCare.Booking.Api/Dockerfile
    container_name: petcare_booking
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__BookingDatabase: "Server=192.168.1.54,1433;Database=PetCareBookingDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Jwt__Secret: "TuClaveSuperSecreta!123!CambiaEstoEnProduccion"
      Jwt__Issuer: "http://petcare_auth"
      Jwt__Audience: "PetCareClientApp"
    ports:
      - "5003:80"
    networks:
      - petcare_net
    depends_on:
      - auth-api

  review-api:
    build:
      context: .
      dockerfile: Review/PetCare.Review.Api/Dockerfile
    container_name: petcare_review
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ReviewDatabase: "Server=192.168.1.54,1433;Database=PetCareReviewDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Jwt__Secret: "TuClaveSuperSecreta!123!CambiaEstoEnProduccion"
      Jwt__Issuer: "http://petcare_auth"
      Jwt__Audience: "PetCareClientApp"
    ports:
      - "5010:80"
    networks:
      - petcare_net
    depends_on:
      - auth-api
      - booking-api

  notification-api:
    build:
      context: .
      dockerfile: Notification/PetCare.Notification.Api/Dockerfile
    container_name: petcare_notification
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__NotificationDatabase: "Server=192.168.1.54,1433;Database=PetCareNotificationDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Kafka__BootstrapServers: "petcare_kafka:9092"
      Kafka__Topic: "notification-events"
      Kafka__ClientId: "notification-producer"
      Kafka__RetryCount: 3
      Kafka__MessageTimeoutMs: 10000
      Kafka__EnableDebugLogging: true
      Kafka__SecurityProtocol: "PLAINTEXT"
      Kafka__Acks: "all"
      Kafka__CompressionType: "gzip"
    ports:
      - "5005:80"
    networks:
      - petcare_net
    depends_on:
      - kafka

  payment-api:
    build:
      context: .
      dockerfile: Payment/PetCare.Payment.Api/Dockerfile
    container_name: petcare_payment
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PaymentDatabase: "Server=192.168.1.54,1433;Database=PetCarePaymentDb;User Id=petcare_user;Password=Nivacathy2033$#;TrustServerCertificate=true;"
      Jwt__Secret: "TuClaveSuperSecreta!123!CambiaEstoEnProduccion"
      Jwt__Issuer: "http://petcare_auth"
      Jwt__Audience: "PetCareClientApp"
    ports:
      - "5006:80"
    networks:
      - petcare_net
    depends_on:
      - pets-api
      - auth-api
