version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petcare_sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

  auth-api:
    build:
      context: .
      dockerfile: Auth/PetCare.Auth.Api/Dockerfile
    container_name: petcare_auth
    ports:
      - "5001:80"
    depends_on:
      - sqlserver

  pets-api:
    build:
      context: .
      dockerfile: Pets/PetCare.Pets.Api/Dockerfile
    container_name: petcare_pets
    ports:
      - "5002:80"
    depends_on:
      - sqlserver

  booking-api:
    build:
      context: .
      dockerfile: Booking/PetCare.Booking.Api/Dockerfile
    container_name: petcare_booking
    ports:
      - "5003:80"
    depends_on:
      - sqlserver

  review-api:
    build:
      context: .
      dockerfile: Review/PetCare.Review.Api/Dockerfile
    container_name: petcare_review
    ports:
      - "5004:80"
    depends_on:
      - sqlserver

  notification-api:
    build:
      context: .
      dockerfile: Notification/PetCare.Notification.Api/Dockerfile
    container_name: petcare_notification
    ports:
      - "5005:80"
    depends_on:
      - sqlserver

  payment-api:
    build:
      context: .
      dockerfile: Payment/PetCare.Payment.Api/Dockerfile
    container_name: petcare_payment
    ports:
      - "5006:80"
    depends_on:
      - sqlserver
      - pets-api

volumes:
  sqlvolume:
