version: "3.9"

services:
  sqlserver:
    environment:
      - MSSQL_PID=Developer
    volumes:
      - sqlvolume:/var/opt/mssql

  auth-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  pets-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  booking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  review-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"

  notification-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"

  payment-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5006:80"

volumes:
  sqlvolume:
