FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base

# Configuración para evitar duplicados en los repositorios
RUN rm -f /etc/apt/sources.list.d/microsoft-prod.list

# Instalación de herramientas MSSQL y configuración de enlaces simbólicos
RUN apt-get update && \
    apt-get install -y curl gnupg apt-transport-https && \
    curl https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor > /usr/share/keyrings/microsoft.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" \
    > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev && \
    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc && \
    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> /etc/profile && \
    ln -sf /opt/mssql-tools18/bin/sqlcmd /usr/bin/sqlcmd && \
    ln -sf /opt/mssql-tools18/bin/bcp /usr/bin/bcp
